/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "primary-fixed": "#d5e3ff",
        "background": "#f7f9fb",
        "on-background": "#191c1e",
        "surface-variant": "#e0e3e5",
        "surface-container-low": "#f2f4f6",
        "inverse-on-surface": "#eff1f3",
        "on-tertiary": "#ffffff",
        "surface-container-high": "#e6e8ea",
        "primary-fixed-dim": "#a7c8ff",
        "on-primary-fixed-variant": "#124782",
        "tertiary-fixed": "#d5e4f3",
        "error-container": "#ffdad6",
        "surface-container": "#eceef0",
        "surface-dim": "#d8dadc",
        "surface-bright": "#f7f9fb",
        "on-error-container": "#93000a",
        "on-tertiary-container": "#b2c0cf",
        "on-tertiary-fixed": "#0f1d28",
        "on-secondary-container": "#003b6a",
        "on-primary-fixed": "#001c3b",
        "on-surface": "#191c1e",
        "surface-tint": "#325f9b",
        "on-secondary-fixed": "#001c38",
        "secondary-container": "#59a6fd",
        "surface-container-highest": "#e0e3e5",
        "tertiary-container": "#414f5b",
        "on-secondary-fixed-variant": "#004881",
        "on-surface-variant": "#424750",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#a2c9ff",
        "primary": "#00376c",
        "tertiary": "#2a3844",
        "inverse-primary": "#a7c8ff",
        "on-tertiary-fixed-variant": "#3a4854",
        "outline-variant": "#c3c6d1",
        "on-primary-container": "#9ac1ff",
        "secondary-fixed": "#d3e4ff",
        "primary-container": "#1d4e89",
        "inverse-surface": "#2d3133",
        "surface-container-lowest": "#ffffff",
        "surface": "#f7f9fb",
        "error": "#ba1a1a",
        "secondary": "#0060a9",
        "outline": "#737781",
        "tertiary-fixed-dim": "#b9c8d7"
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "sm": "0.25rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "unit": "8px",
        "container-max": "1280px",
        "margin-desktop": "64px",
        "gutter": "24px",
        "margin-mobile": "20px"
      },
      fontFamily: {
        "display-lg": ["Hanken Grotesk", "sans-serif"],
        "caption": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Hanken Grotesk", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "label-md": ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"]
      },
      fontSize: {
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "caption": ["12px", { "lineHeight": "16px", "fontWeight": "400" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "36px", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "fontWeight": "700" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}